package storm_falcon.fields;

import com.portal.pcm.StrField;

/**
 * Specific Field subclasses. This subclasses of <code>Field</code>
 * is used with the FList class to specifiy which field is being
 * accessed, and its type.  The type information is used to provide
 * compile time type checking.  These classes are auto generated.
 * @version 1.0 Wed Nov 28 13:54:46 CST 2007
 * @author Autogenerated
 */


public class CpFldVlanIdS extends StrField {

	/**
	 * Constructs an instance of <code>CpFldVlanIdS</code>
	 */
	public CpFldVlanIdS() { super(10105, 5); }

	/**
	 * Returns an instance of <code>CpFldVlanIdS</code>
	 * @return An instance of <code>CpFldVlanIdS</code>
	 */
	public static synchronized CpFldVlanIdS getInst() { 
		if( me == null ) me = new CpFldVlanIdS();
		return me;
	}
	private static CpFldVlanIdS me;
}
