package storm_falcon.fields;

import com.portal.pcm.PoidField;

/**
 * Specific Field subclasses. This subclasses of <code>Field</code>
 * is used with the FList class to specifiy which field is being
 * accessed, and its type.  The type information is used to provide
 * compile time type checking.  These classes are auto generated.
 * @version 1.0 Wed Nov 28 13:54:46 CST 2007
 * @author Autogenerated
 */


public class CpFldChangeManagePoid extends PoidField {

	/**
	 * Constructs an instance of <code>CpFldChangeManagePoid</code>
	 */
	public CpFldChangeManagePoid() { super(10122, 7); }

	/**
	 * Returns an instance of <code>CpFldChangeManagePoid</code>
	 * @return An instance of <code>CpFldChangeManagePoid</code>
	 */
	public static synchronized CpFldChangeManagePoid getInst() { 
		if( me == null ) me = new CpFldChangeManagePoid();
		return me;
	}
	private static CpFldChangeManagePoid me;
}
