package storm_falcon.fields;

import com.portal.pcm.EnumField;

/**
 * Specific Field subclasses. This subclasses of <code>Field</code>
 * is used with the FList class to specifiy which field is being
 * accessed, and its type.  The type information is used to provide
 * compile time type checking.  These classes are auto generated.
 * @version 1.0 Wed Nov 28 13:54:46 CST 2007
 * @author Autogenerated
 */


public class CpFldPriceType extends EnumField {

	/**
	 * Constructs an instance of <code>CpFldPriceType</code>
	 */
	public CpFldPriceType() { super(10065, 3); }

	/**
	 * Returns an instance of <code>CpFldPriceType</code>
	 * @return An instance of <code>CpFldPriceType</code>
	 */
	public static synchronized CpFldPriceType getInst() { 
		if( me == null ) me = new CpFldPriceType();
		return me;
	}
	private static CpFldPriceType me;
}
