package storm_falcon.fields;

import com.portal.pcm.ArrayField;

/**
 * Specific Field subclasses. This subclasses of <code>Field</code>
 * is used with the FList class to specifiy which field is being
 * accessed, and its type.  The type information is used to provide
 * compile time type checking.  These classes are auto generated.
 * @version 1.0 Wed Nov 28 13:54:46 CST 2007
 * @author Autogenerated
 */


public class CpFldValidtod extends ArrayField {

	/**
	 * Constructs an instance of <code>CpFldValidtod</code>
	 */
	public CpFldValidtod() { super(10013, 9); }

	/**
	 * Returns an instance of <code>CpFldValidtod</code>
	 * @return An instance of <code>CpFldValidtod</code>
	 */
	public static synchronized CpFldValidtod getInst() { 
		if( me == null ) me = new CpFldValidtod();
		return me;
	}
	private static CpFldValidtod me;
}
