package storm_falcon.fields;

import com.portal.pcm.SubStructField;

/**
 * Specific Field subclasses. This subclasses of <code>Field</code>
 * is used with the FList class to specifiy which field is being
 * accessed, and its type.  The type information is used to provide
 * compile time type checking.  These classes are auto generated.
 * @version 1.0 Wed Nov 28 13:54:46 CST 2007
 * @author Autogenerated
 */


public class CpFldCustinfo extends SubStructField {

	/**
	 * Constructs an instance of <code>CpFldCustinfo</code>
	 */
	public CpFldCustinfo() { super(10047, 10); }

	/**
	 * Returns an instance of <code>CpFldCustinfo</code>
	 * @return An instance of <code>CpFldCustinfo</code>
	 */
	public static synchronized CpFldCustinfo getInst() { 
		if( me == null ) me = new CpFldCustinfo();
		return me;
	}
	private static CpFldCustinfo me;
}
