package storm_falcon.fields;

import com.portal.pcm.TStampField;

/**
 * Specific Field subclasses. This subclasses of <code>Field</code>
 * is used with the FList class to specifiy which field is being
 * accessed, and its type.  The type information is used to provide
 * compile time type checking.  These classes are auto generated.
 * @version 1.0 Wed Nov 28 13:54:46 CST 2007
 * @author Autogenerated
 */


public class CpFldBeginDate extends TStampField {

	/**
	 * Constructs an instance of <code>CpFldBeginDate</code>
	 */
	public CpFldBeginDate() { super(10069, 8); }

	/**
	 * Returns an instance of <code>CpFldBeginDate</code>
	 * @return An instance of <code>CpFldBeginDate</code>
	 */
	public static synchronized CpFldBeginDate getInst() { 
		if( me == null ) me = new CpFldBeginDate();
		return me;
	}
	private static CpFldBeginDate me;
}
