package storm_falcon.fields;

import com.portal.pcm.StrField;

/**
 * Specific Field subclasses. This subclasses of <code>Field</code>
 * is used with the FList class to specifiy which field is being
 * accessed, and its type.  The type information is used to provide
 * compile time type checking.  These classes are auto generated.
 * @version 1.0 Tue Nov 19 03:37:41 GMT 2013
 * @author Autogenerated
 */


public class PinFldIpv6Address extends StrField {

	/**
	 * Constructs an instance of <code>PinFldIpv6Address</code>
	 */
	public PinFldIpv6Address() { super(10136, 5); }

	/**
	 * Returns an instance of <code>PinFldIpv6Address</code>
	 * @return An instance of <code>PinFldIpv6Address</code>
	 */
	public static synchronized PinFldIpv6Address getInst() { 
		if( me == null ) me = new PinFldIpv6Address();
		return me;
	}
	private static PinFldIpv6Address me;
}
